package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallgoodslog;

public interface MallgoodslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallgoodslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallgoodslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallgoodslog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallgoodslog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodslog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallgoodslog record);
}