package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallpaymentlog;

public interface MallpaymentlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallpaymentlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallpaymentlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallpaymentlog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallpaymentlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpaymentlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallpaymentlog record);
}