package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallpayment;

public interface MallpaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallpayment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallpayment
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallpayment record);
}