package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallshopdetail;

public interface MallshopdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallshopdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallshopdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallshopdetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallshopdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallshopdetail record);
}