package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallgoods;

public interface MallgoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallgoods selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallgoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoods
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallgoods record);
}