package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Malluser;

public interface MalluserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Malluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Malluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Malluser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Malluser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluser
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Malluser record);
}