package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallorder;

public interface MallorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallorder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorder
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallorder record);
}