package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallgoodskind;

public interface MallgoodskindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallgoodskind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallgoodskind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallgoodskind selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallgoodskind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodskind
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallgoodskind record);
}