package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallgoodspicture;

public interface MallgoodspictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallgoodspicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallgoodspicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallgoodspicture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallgoodspicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallgoodspicture
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallgoodspicture record);
}