package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallshopfee;

public interface MallshopfeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallshopfee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallshopfee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallshopfee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallshopfee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshopfee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallshopfee record);
}