package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallorderdetail;

public interface MallorderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallorderdetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallorderdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallorderdetail record);
}