package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallbannerdetail;

public interface MallbannerdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallbannerdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallbannerdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallbannerdetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallbannerdetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbannerdetail
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallbannerdetail record);
}