package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Malluserlogin;

public interface MalluserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Malluserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Malluserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Malluserlogin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Malluserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluserlogin
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Malluserlogin record);
}