package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallshoplog;

public interface MallshoplogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallshoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallshoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallshoplog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallshoplog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallshoplog record);
}