package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallshoplicense;

public interface MallshoplicenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallshoplicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallshoplicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallshoplicense selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallshoplicense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallshoplicense
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallshoplicense record);
}