package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallbanner;

public interface MallbannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallbanner selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallbanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallbanner
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallbanner record);
}