package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Malluseraddress;

public interface MalluseraddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Malluseraddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Malluseraddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Malluseraddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Malluseraddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malluseraddress
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Malluseraddress record);
}