package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallorderpay;

public interface MallorderpayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallorderpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallorderpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallorderpay selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallorderpay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderpay
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallorderpay record);
}