package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallorderlog;

public interface MallorderlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallorderlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallorderlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallorderlog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallorderlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallorderlog
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallorderlog record);
}