package com.microshop.servicedao.mapper;

import com.microshop.servicedao.dbmodel.Mallcategory;

public interface MallcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insert(Mallcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int insertSelective(Mallcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    Mallcategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKeySelective(Mallcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mallcategory
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    int updateByPrimaryKey(Mallcategory record);
}