package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallgoodslog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.kindId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String kindid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.content
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.logType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String logtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodslog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.id
     *
     * @return the value of mallgoodslog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.id
     *
     * @param id the value for mallgoodslog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.goodsId
     *
     * @return the value of mallgoodslog.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.goodsId
     *
     * @param goodsid the value for mallgoodslog.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.kindId
     *
     * @return the value of mallgoodslog.kindId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getKindid() {
        return kindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.kindId
     *
     * @param kindid the value for mallgoodslog.kindId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setKindid(String kindid) {
        this.kindid = kindid == null ? null : kindid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.userName
     *
     * @return the value of mallgoodslog.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.userName
     *
     * @param username the value for mallgoodslog.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.userId
     *
     * @return the value of mallgoodslog.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.userId
     *
     * @param userid the value for mallgoodslog.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.content
     *
     * @return the value of mallgoodslog.content
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.content
     *
     * @param content the value for mallgoodslog.content
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.logType
     *
     * @return the value of mallgoodslog.logType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.logType
     *
     * @param logtype the value for mallgoodslog.logType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype == null ? null : logtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.flowStatus
     *
     * @return the value of mallgoodslog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.flowStatus
     *
     * @param flowstatus the value for mallgoodslog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodslog.createTime
     *
     * @return the value of mallgoodslog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodslog.createTime
     *
     * @param createtime the value for mallgoodslog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}