package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallbanner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String pictureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.timeLength
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer timelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.stopTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date stoptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer platformid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.showType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer showtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.bannerType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer bannertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.targetUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String targeturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallbanner.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.id
     *
     * @return the value of mallbanner.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.id
     *
     * @param id the value for mallbanner.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.name
     *
     * @return the value of mallbanner.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.name
     *
     * @param name the value for mallbanner.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.pictureUrl
     *
     * @return the value of mallbanner.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPictureurl() {
        return pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.pictureUrl
     *
     * @param pictureurl the value for mallbanner.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl == null ? null : pictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.sort
     *
     * @return the value of mallbanner.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.sort
     *
     * @param sort the value for mallbanner.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.timeLength
     *
     * @return the value of mallbanner.timeLength
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTimelength() {
        return timelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.timeLength
     *
     * @param timelength the value for mallbanner.timeLength
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTimelength(Integer timelength) {
        this.timelength = timelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.startTime
     *
     * @return the value of mallbanner.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.startTime
     *
     * @param starttime the value for mallbanner.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.stopTime
     *
     * @return the value of mallbanner.stopTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.stopTime
     *
     * @param stoptime the value for mallbanner.stopTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStoptime(Date stoptime) {
        this.stoptime = stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.platformId
     *
     * @return the value of mallbanner.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPlatformid() {
        return platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.platformId
     *
     * @param platformid the value for mallbanner.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPlatformid(Integer platformid) {
        this.platformid = platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.showType
     *
     * @return the value of mallbanner.showType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.showType
     *
     * @param showtype the value for mallbanner.showType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShowtype(Integer showtype) {
        this.showtype = showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.bannerType
     *
     * @return the value of mallbanner.bannerType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getBannertype() {
        return bannertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.bannerType
     *
     * @param bannertype the value for mallbanner.bannerType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBannertype(Integer bannertype) {
        this.bannertype = bannertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.targetUrl
     *
     * @return the value of mallbanner.targetUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTargeturl() {
        return targeturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.targetUrl
     *
     * @param targeturl the value for mallbanner.targetUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTargeturl(String targeturl) {
        this.targeturl = targeturl == null ? null : targeturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.state
     *
     * @return the value of mallbanner.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.state
     *
     * @param state the value for mallbanner.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.createTime
     *
     * @return the value of mallbanner.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.createTime
     *
     * @param createtime the value for mallbanner.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.updateTime
     *
     * @return the value of mallbanner.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.updateTime
     *
     * @param updatetime the value for mallbanner.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.userId
     *
     * @return the value of mallbanner.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.userId
     *
     * @param userid the value for mallbanner.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.userName
     *
     * @return the value of mallbanner.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.userName
     *
     * @param username the value for mallbanner.userName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallbanner.remark
     *
     * @return the value of mallbanner.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallbanner.remark
     *
     * @param remark the value for mallbanner.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}