package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.logourl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String logourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.contactName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String contactname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.contactPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String contactphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.loginId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String loginid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.openTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date opentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.shopDetailUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopdetailurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshop.endTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.id
     *
     * @return the value of mallshop.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.id
     *
     * @param id the value for mallshop.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.name
     *
     * @return the value of mallshop.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.name
     *
     * @param name the value for mallshop.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.logourl
     *
     * @return the value of mallshop.logourl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.logourl
     *
     * @param logourl the value for mallshop.logourl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl == null ? null : logourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.contactName
     *
     * @return the value of mallshop.contactName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.contactName
     *
     * @param contactname the value for mallshop.contactName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.contactPhone
     *
     * @return the value of mallshop.contactPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.contactPhone
     *
     * @param contactphone the value for mallshop.contactPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.provinceId
     *
     * @return the value of mallshop.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.provinceId
     *
     * @param provinceid the value for mallshop.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.cityId
     *
     * @return the value of mallshop.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.cityId
     *
     * @param cityid the value for mallshop.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.areaId
     *
     * @return the value of mallshop.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.areaId
     *
     * @param areaid the value for mallshop.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.loginId
     *
     * @return the value of mallshop.loginId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLoginid() {
        return loginid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.loginId
     *
     * @param loginid the value for mallshop.loginId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLoginid(String loginid) {
        this.loginid = loginid == null ? null : loginid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.userId
     *
     * @return the value of mallshop.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.userId
     *
     * @param userid the value for mallshop.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.openTime
     *
     * @return the value of mallshop.openTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.openTime
     *
     * @param opentime the value for mallshop.openTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.shopDetailUrl
     *
     * @return the value of mallshop.shopDetailUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopdetailurl() {
        return shopdetailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.shopDetailUrl
     *
     * @param shopdetailurl the value for mallshop.shopDetailUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopdetailurl(String shopdetailurl) {
        this.shopdetailurl = shopdetailurl == null ? null : shopdetailurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.flowStatus
     *
     * @return the value of mallshop.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.flowStatus
     *
     * @param flowstatus the value for mallshop.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.state
     *
     * @return the value of mallshop.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.state
     *
     * @param state the value for mallshop.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.createTime
     *
     * @return the value of mallshop.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.createTime
     *
     * @param createtime the value for mallshop.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.startTime
     *
     * @return the value of mallshop.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.startTime
     *
     * @param starttime the value for mallshop.startTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshop.endTime
     *
     * @return the value of mallshop.endTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshop.endTime
     *
     * @param endtime the value for mallshop.endTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}