package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Malluserlogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.loginName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.loginPwd
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String loginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.loginType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer logintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer platformid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.userType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluserlogin.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.id
     *
     * @return the value of malluserlogin.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.id
     *
     * @param id the value for malluserlogin.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.userId
     *
     * @return the value of malluserlogin.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.userId
     *
     * @param userid the value for malluserlogin.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.loginName
     *
     * @return the value of malluserlogin.loginName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.loginName
     *
     * @param loginname the value for malluserlogin.loginName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.loginPwd
     *
     * @return the value of malluserlogin.loginPwd
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.loginPwd
     *
     * @param loginpwd the value for malluserlogin.loginPwd
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.loginType
     *
     * @return the value of malluserlogin.loginType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.loginType
     *
     * @param logintype the value for malluserlogin.loginType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLogintype(Integer logintype) {
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.platformId
     *
     * @return the value of malluserlogin.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPlatformid() {
        return platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.platformId
     *
     * @param platformid the value for malluserlogin.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPlatformid(Integer platformid) {
        this.platformid = platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.userType
     *
     * @return the value of malluserlogin.userType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.userType
     *
     * @param usertype the value for malluserlogin.userType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.state
     *
     * @return the value of malluserlogin.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.state
     *
     * @param state the value for malluserlogin.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluserlogin.createTime
     *
     * @return the value of malluserlogin.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluserlogin.createTime
     *
     * @param createtime the value for malluserlogin.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}