package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Malluseraddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.phone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.defaultAddr
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer defaultaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column malluseraddress.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.id
     *
     * @return the value of malluseraddress.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.id
     *
     * @param id the value for malluseraddress.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.userId
     *
     * @return the value of malluseraddress.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.userId
     *
     * @param userid the value for malluseraddress.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.provinceId
     *
     * @return the value of malluseraddress.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.provinceId
     *
     * @param provinceid the value for malluseraddress.provinceId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.cityId
     *
     * @return the value of malluseraddress.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.cityId
     *
     * @param cityid the value for malluseraddress.cityId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.areaId
     *
     * @return the value of malluseraddress.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.areaId
     *
     * @param areaid the value for malluseraddress.areaId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.name
     *
     * @return the value of malluseraddress.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.name
     *
     * @param name the value for malluseraddress.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.phone
     *
     * @return the value of malluseraddress.phone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.phone
     *
     * @param phone the value for malluseraddress.phone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.address
     *
     * @return the value of malluseraddress.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.address
     *
     * @param address the value for malluseraddress.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.defaultAddr
     *
     * @return the value of malluseraddress.defaultAddr
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getDefaultaddr() {
        return defaultaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.defaultAddr
     *
     * @param defaultaddr the value for malluseraddress.defaultAddr
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setDefaultaddr(Integer defaultaddr) {
        this.defaultaddr = defaultaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.state
     *
     * @return the value of malluseraddress.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.state
     *
     * @param state the value for malluseraddress.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column malluseraddress.createTime
     *
     * @return the value of malluseraddress.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column malluseraddress.createTime
     *
     * @param createtime the value for malluseraddress.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}