package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallorderpay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer payprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String payflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.thirdFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String thirdflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderpay.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.id
     *
     * @return the value of mallorderpay.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.id
     *
     * @param id the value for mallorderpay.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.orderId
     *
     * @return the value of mallorderpay.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.orderId
     *
     * @param orderid the value for mallorderpay.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.shopId
     *
     * @return the value of mallorderpay.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.shopId
     *
     * @param shopid the value for mallorderpay.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.userId
     *
     * @return the value of mallorderpay.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.userId
     *
     * @param userid the value for mallorderpay.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.payType
     *
     * @return the value of mallorderpay.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.payType
     *
     * @param paytype the value for mallorderpay.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.payPrice
     *
     * @return the value of mallorderpay.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPayprice() {
        return payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.payPrice
     *
     * @param payprice the value for mallorderpay.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayprice(Integer payprice) {
        this.payprice = payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.payFlow
     *
     * @return the value of mallorderpay.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPayflow() {
        return payflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.payFlow
     *
     * @param payflow the value for mallorderpay.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayflow(String payflow) {
        this.payflow = payflow == null ? null : payflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.thirdFlow
     *
     * @return the value of mallorderpay.thirdFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getThirdflow() {
        return thirdflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.thirdFlow
     *
     * @param thirdflow the value for mallorderpay.thirdFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setThirdflow(String thirdflow) {
        this.thirdflow = thirdflow == null ? null : thirdflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.flowStatus
     *
     * @return the value of mallorderpay.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.flowStatus
     *
     * @param flowstatus the value for mallorderpay.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderpay.createTime
     *
     * @return the value of mallorderpay.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderpay.createTime
     *
     * @param createtime the value for mallorderpay.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}