package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallorderdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.relationId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String relationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.relationType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer relationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer standardprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer costprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer trafficprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer payprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.id
     *
     * @return the value of mallorderdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.id
     *
     * @param id the value for mallorderdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.orderId
     *
     * @return the value of mallorderdetail.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.orderId
     *
     * @param orderid the value for mallorderdetail.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.relationId
     *
     * @return the value of mallorderdetail.relationId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getRelationid() {
        return relationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.relationId
     *
     * @param relationid the value for mallorderdetail.relationId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setRelationid(String relationid) {
        this.relationid = relationid == null ? null : relationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.shopId
     *
     * @return the value of mallorderdetail.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.shopId
     *
     * @param shopid the value for mallorderdetail.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.relationType
     *
     * @return the value of mallorderdetail.relationType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getRelationtype() {
        return relationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.relationType
     *
     * @param relationtype the value for mallorderdetail.relationType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setRelationtype(Integer relationtype) {
        this.relationtype = relationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.standardPrice
     *
     * @return the value of mallorderdetail.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getStandardprice() {
        return standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.standardPrice
     *
     * @param standardprice the value for mallorderdetail.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStandardprice(Integer standardprice) {
        this.standardprice = standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.salePrice
     *
     * @return the value of mallorderdetail.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.salePrice
     *
     * @param saleprice the value for mallorderdetail.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSaleprice(Integer saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.costPrice
     *
     * @return the value of mallorderdetail.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.costPrice
     *
     * @param costprice the value for mallorderdetail.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCostprice(Integer costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.trafficPrice
     *
     * @return the value of mallorderdetail.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTrafficprice() {
        return trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.trafficPrice
     *
     * @param trafficprice the value for mallorderdetail.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTrafficprice(Integer trafficprice) {
        this.trafficprice = trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.payPrice
     *
     * @return the value of mallorderdetail.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPayprice() {
        return payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.payPrice
     *
     * @param payprice the value for mallorderdetail.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayprice(Integer payprice) {
        this.payprice = payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderdetail.createTime
     *
     * @return the value of mallorderdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderdetail.createTime
     *
     * @param createtime the value for mallorderdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}