package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallgoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String brandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer firstcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer secondcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer thirdcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.title
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer standardprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer costprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.keywords
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String logourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.saleTotal
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer saletotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoods.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.id
     *
     * @return the value of mallgoods.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.id
     *
     * @param id the value for mallgoods.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.name
     *
     * @return the value of mallgoods.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.name
     *
     * @param name the value for mallgoods.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.brandName
     *
     * @return the value of mallgoods.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.brandName
     *
     * @param brandname the value for mallgoods.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.shopId
     *
     * @return the value of mallgoods.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.shopId
     *
     * @param shopid the value for mallgoods.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.firstCategoryId
     *
     * @return the value of mallgoods.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFirstcategoryid() {
        return firstcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.firstCategoryId
     *
     * @param firstcategoryid the value for mallgoods.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFirstcategoryid(Integer firstcategoryid) {
        this.firstcategoryid = firstcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.secondCategoryId
     *
     * @return the value of mallgoods.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSecondcategoryid() {
        return secondcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.secondCategoryId
     *
     * @param secondcategoryid the value for mallgoods.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSecondcategoryid(Integer secondcategoryid) {
        this.secondcategoryid = secondcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.categoryName
     *
     * @return the value of mallgoods.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.categoryName
     *
     * @param categoryname the value for mallgoods.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.thirdCategoryId
     *
     * @return the value of mallgoods.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getThirdcategoryid() {
        return thirdcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.thirdCategoryId
     *
     * @param thirdcategoryid the value for mallgoods.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setThirdcategoryid(Integer thirdcategoryid) {
        this.thirdcategoryid = thirdcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.title
     *
     * @return the value of mallgoods.title
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.title
     *
     * @param title the value for mallgoods.title
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.standardPrice
     *
     * @return the value of mallgoods.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getStandardprice() {
        return standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.standardPrice
     *
     * @param standardprice the value for mallgoods.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStandardprice(Integer standardprice) {
        this.standardprice = standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.salePrice
     *
     * @return the value of mallgoods.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.salePrice
     *
     * @param saleprice the value for mallgoods.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSaleprice(Integer saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.costPrice
     *
     * @return the value of mallgoods.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.costPrice
     *
     * @param costprice the value for mallgoods.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCostprice(Integer costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.keywords
     *
     * @return the value of mallgoods.keywords
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.keywords
     *
     * @param keywords the value for mallgoods.keywords
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.logoUrl
     *
     * @return the value of mallgoods.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.logoUrl
     *
     * @param logourl the value for mallgoods.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl == null ? null : logourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.remark
     *
     * @return the value of mallgoods.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.remark
     *
     * @param remark the value for mallgoods.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.flowStatus
     *
     * @return the value of mallgoods.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.flowStatus
     *
     * @param flowstatus the value for mallgoods.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.saleTotal
     *
     * @return the value of mallgoods.saleTotal
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSaletotal() {
        return saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.saleTotal
     *
     * @param saletotal the value for mallgoods.saleTotal
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSaletotal(Integer saletotal) {
        this.saletotal = saletotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.state
     *
     * @return the value of mallgoods.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.state
     *
     * @param state the value for mallgoods.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoods.createTime
     *
     * @return the value of mallgoods.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoods.createTime
     *
     * @param createtime the value for mallgoods.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}