package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallpaymentlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String payid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer payfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String payflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpaymentlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.id
     *
     * @return the value of mallpaymentlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.id
     *
     * @param id the value for mallpaymentlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payId
     *
     * @return the value of mallpaymentlog.payId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payId
     *
     * @param payid the value for mallpaymentlog.payId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayid(String payid) {
        this.payid = payid == null ? null : payid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payType
     *
     * @return the value of mallpaymentlog.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payType
     *
     * @param paytype the value for mallpaymentlog.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payMoney
     *
     * @return the value of mallpaymentlog.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payMoney
     *
     * @param paymoney the value for mallpaymentlog.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaymoney(Integer paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payFee
     *
     * @return the value of mallpaymentlog.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPayfee() {
        return payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payFee
     *
     * @param payfee the value for mallpaymentlog.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayfee(Integer payfee) {
        this.payfee = payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payStatus
     *
     * @return the value of mallpaymentlog.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payStatus
     *
     * @param paystatus the value for mallpaymentlog.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.payFlow
     *
     * @return the value of mallpaymentlog.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPayflow() {
        return payflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.payFlow
     *
     * @param payflow the value for mallpaymentlog.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayflow(String payflow) {
        this.payflow = payflow == null ? null : payflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpaymentlog.createTime
     *
     * @return the value of mallpaymentlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpaymentlog.createTime
     *
     * @param createtime the value for mallpaymentlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}