package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallpayment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.Id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer platformid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.applyFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String applyflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer payfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String payflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.updateTim
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date updatetim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallpayment.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.Id
     *
     * @return the value of mallpayment.Id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.Id
     *
     * @param id the value for mallpayment.Id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.platformId
     *
     * @return the value of mallpayment.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPlatformid() {
        return platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.platformId
     *
     * @param platformid the value for mallpayment.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPlatformid(Integer platformid) {
        this.platformid = platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.applyFlow
     *
     * @return the value of mallpayment.applyFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getApplyflow() {
        return applyflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.applyFlow
     *
     * @param applyflow the value for mallpayment.applyFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setApplyflow(String applyflow) {
        this.applyflow = applyflow == null ? null : applyflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.payType
     *
     * @return the value of mallpayment.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.payType
     *
     * @param paytype the value for mallpayment.payType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.payMoney
     *
     * @return the value of mallpayment.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.payMoney
     *
     * @param paymoney the value for mallpayment.payMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaymoney(Integer paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.payFee
     *
     * @return the value of mallpayment.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPayfee() {
        return payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.payFee
     *
     * @param payfee the value for mallpayment.payFee
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayfee(Integer payfee) {
        this.payfee = payfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.payStatus
     *
     * @return the value of mallpayment.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.payStatus
     *
     * @param paystatus the value for mallpayment.payStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.payFlow
     *
     * @return the value of mallpayment.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPayflow() {
        return payflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.payFlow
     *
     * @param payflow the value for mallpayment.payFlow
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayflow(String payflow) {
        this.payflow = payflow == null ? null : payflow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.updateTim
     *
     * @return the value of mallpayment.updateTim
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getUpdatetim() {
        return updatetim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.updateTim
     *
     * @param updatetim the value for mallpayment.updateTim
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUpdatetim(Date updatetim) {
        this.updatetim = updatetim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallpayment.createTime
     *
     * @return the value of mallpayment.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallpayment.createTime
     *
     * @param createtime the value for mallpayment.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}