package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer platformid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.targetId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String targetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.targetName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String targetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.targetPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String targetphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer standardprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer costprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer trafficprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer payprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorder.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.id
     *
     * @return the value of mallorder.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.id
     *
     * @param id the value for mallorder.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.userId
     *
     * @return the value of mallorder.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.userId
     *
     * @param userid the value for mallorder.userId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.platformId
     *
     * @return the value of mallorder.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPlatformid() {
        return platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.platformId
     *
     * @param platformid the value for mallorder.platformId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPlatformid(Integer platformid) {
        this.platformid = platformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.targetId
     *
     * @return the value of mallorder.targetId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.targetId
     *
     * @param targetid the value for mallorder.targetId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTargetid(String targetid) {
        this.targetid = targetid == null ? null : targetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.targetName
     *
     * @return the value of mallorder.targetName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTargetname() {
        return targetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.targetName
     *
     * @param targetname the value for mallorder.targetName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTargetname(String targetname) {
        this.targetname = targetname == null ? null : targetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.targetPhone
     *
     * @return the value of mallorder.targetPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTargetphone() {
        return targetphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.targetPhone
     *
     * @param targetphone the value for mallorder.targetPhone
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTargetphone(String targetphone) {
        this.targetphone = targetphone == null ? null : targetphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.standardPrice
     *
     * @return the value of mallorder.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getStandardprice() {
        return standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.standardPrice
     *
     * @param standardprice the value for mallorder.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStandardprice(Integer standardprice) {
        this.standardprice = standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.salePrice
     *
     * @return the value of mallorder.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.salePrice
     *
     * @param saleprice the value for mallorder.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSaleprice(Integer saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.costPrice
     *
     * @return the value of mallorder.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.costPrice
     *
     * @param costprice the value for mallorder.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCostprice(Integer costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.trafficPrice
     *
     * @return the value of mallorder.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTrafficprice() {
        return trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.trafficPrice
     *
     * @param trafficprice the value for mallorder.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTrafficprice(Integer trafficprice) {
        this.trafficprice = trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.payPrice
     *
     * @return the value of mallorder.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getPayprice() {
        return payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.payPrice
     *
     * @param payprice the value for mallorder.payPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPayprice(Integer payprice) {
        this.payprice = payprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.flowStatus
     *
     * @return the value of mallorder.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.flowStatus
     *
     * @param flowstatus the value for mallorder.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.state
     *
     * @return the value of mallorder.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.state
     *
     * @param state the value for mallorder.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.createTime
     *
     * @return the value of mallorder.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.createTime
     *
     * @param createtime the value for mallorder.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorder.updateTime
     *
     * @return the value of mallorder.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorder.updateTime
     *
     * @param updatetime the value for mallorder.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}