package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallorderlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderlog.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderlog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallorderlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderlog.id
     *
     * @return the value of mallorderlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderlog.id
     *
     * @param id the value for mallorderlog.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderlog.orderId
     *
     * @return the value of mallorderlog.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderlog.orderId
     *
     * @param orderid the value for mallorderlog.orderId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderlog.flowStatus
     *
     * @return the value of mallorderlog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderlog.flowStatus
     *
     * @param flowstatus the value for mallorderlog.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallorderlog.createTime
     *
     * @return the value of mallorderlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallorderlog.createTime
     *
     * @param createtime the value for mallorderlog.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}