package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallshoplicense {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.licenseType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer licensetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.licenseUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String licenseurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshoplicense.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.id
     *
     * @return the value of mallshoplicense.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.id
     *
     * @param id the value for mallshoplicense.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.shopId
     *
     * @return the value of mallshoplicense.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.shopId
     *
     * @param shopid the value for mallshoplicense.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.licenseType
     *
     * @return the value of mallshoplicense.licenseType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getLicensetype() {
        return licensetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.licenseType
     *
     * @param licensetype the value for mallshoplicense.licenseType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLicensetype(Integer licensetype) {
        this.licensetype = licensetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.licenseUrl
     *
     * @return the value of mallshoplicense.licenseUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLicenseurl() {
        return licenseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.licenseUrl
     *
     * @param licenseurl the value for mallshoplicense.licenseUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLicenseurl(String licenseurl) {
        this.licenseurl = licenseurl == null ? null : licenseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.state
     *
     * @return the value of mallshoplicense.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.state
     *
     * @param state the value for mallshoplicense.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshoplicense.createTime
     *
     * @return the value of mallshoplicense.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshoplicense.createTime
     *
     * @param createtime the value for mallshoplicense.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}