package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallshopdetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.email
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.companyName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.taxCheck
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String taxcheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.bankName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String bankname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.bankAccount
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String bankaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.id
     *
     * @return the value of mallshopdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.id
     *
     * @param id the value for mallshopdetail.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.email
     *
     * @return the value of mallshopdetail.email
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.email
     *
     * @param email the value for mallshopdetail.email
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.address
     *
     * @return the value of mallshopdetail.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.address
     *
     * @param address the value for mallshopdetail.address
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.companyName
     *
     * @return the value of mallshopdetail.companyName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.companyName
     *
     * @param companyname the value for mallshopdetail.companyName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.taxCheck
     *
     * @return the value of mallshopdetail.taxCheck
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getTaxcheck() {
        return taxcheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.taxCheck
     *
     * @param taxcheck the value for mallshopdetail.taxCheck
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTaxcheck(String taxcheck) {
        this.taxcheck = taxcheck == null ? null : taxcheck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.bankName
     *
     * @return the value of mallshopdetail.bankName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.bankName
     *
     * @param bankname the value for mallshopdetail.bankName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.bankAccount
     *
     * @return the value of mallshopdetail.bankAccount
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.bankAccount
     *
     * @param bankaccount the value for mallshopdetail.bankAccount
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount == null ? null : bankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.remark
     *
     * @return the value of mallshopdetail.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.remark
     *
     * @param remark the value for mallshopdetail.remark
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopdetail.createTime
     *
     * @return the value of mallshopdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopdetail.createTime
     *
     * @param createtime the value for mallshopdetail.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}