package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallshopfee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.feeMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer feemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.feeRate
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer feerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallshopfee.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.id
     *
     * @return the value of mallshopfee.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.id
     *
     * @param id the value for mallshopfee.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.shopName
     *
     * @return the value of mallshopfee.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.shopName
     *
     * @param shopname the value for mallshopfee.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.shopId
     *
     * @return the value of mallshopfee.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.shopId
     *
     * @param shopid the value for mallshopfee.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.feeMoney
     *
     * @return the value of mallshopfee.feeMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFeemoney() {
        return feemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.feeMoney
     *
     * @param feemoney the value for mallshopfee.feeMoney
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFeemoney(Integer feemoney) {
        this.feemoney = feemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.feeRate
     *
     * @return the value of mallshopfee.feeRate
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFeerate() {
        return feerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.feeRate
     *
     * @param feerate the value for mallshopfee.feeRate
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFeerate(Integer feerate) {
        this.feerate = feerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.state
     *
     * @return the value of mallshopfee.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.state
     *
     * @param state the value for mallshopfee.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallshopfee.createTime
     *
     * @return the value of mallshopfee.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallshopfee.createTime
     *
     * @param createtime the value for mallshopfee.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}