package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallgoodskind {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.sku
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.goodsName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String brandname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer thirdcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer secondcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer firstcategoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String categoryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String logourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer standardprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer costprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.barCode
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer trafficprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.trafficType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer traffictype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.stock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.version
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.tempStock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer tempstock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer flowstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.tempVersion
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer tempversion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodskind.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.id
     *
     * @return the value of mallgoodskind.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.id
     *
     * @param id the value for mallgoodskind.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.sku
     *
     * @return the value of mallgoodskind.sku
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.sku
     *
     * @param sku the value for mallgoodskind.sku
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.goodsName
     *
     * @return the value of mallgoodskind.goodsName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.goodsName
     *
     * @param goodsname the value for mallgoodskind.goodsName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.goodsId
     *
     * @return the value of mallgoodskind.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.goodsId
     *
     * @param goodsid the value for mallgoodskind.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.shopId
     *
     * @return the value of mallgoodskind.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.shopId
     *
     * @param shopid the value for mallgoodskind.shopId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopid(String shopid) {
        this.shopid = shopid == null ? null : shopid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.shopName
     *
     * @return the value of mallgoodskind.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.shopName
     *
     * @param shopname the value for mallgoodskind.shopName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.brandName
     *
     * @return the value of mallgoodskind.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.brandName
     *
     * @param brandname the value for mallgoodskind.brandName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.thirdCategoryId
     *
     * @return the value of mallgoodskind.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getThirdcategoryid() {
        return thirdcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.thirdCategoryId
     *
     * @param thirdcategoryid the value for mallgoodskind.thirdCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setThirdcategoryid(Integer thirdcategoryid) {
        this.thirdcategoryid = thirdcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.secondCategoryId
     *
     * @return the value of mallgoodskind.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSecondcategoryid() {
        return secondcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.secondCategoryId
     *
     * @param secondcategoryid the value for mallgoodskind.secondCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSecondcategoryid(Integer secondcategoryid) {
        this.secondcategoryid = secondcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.firstCategoryId
     *
     * @return the value of mallgoodskind.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFirstcategoryid() {
        return firstcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.firstCategoryId
     *
     * @param firstcategoryid the value for mallgoodskind.firstCategoryId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFirstcategoryid(Integer firstcategoryid) {
        this.firstcategoryid = firstcategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.categoryName
     *
     * @return the value of mallgoodskind.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.categoryName
     *
     * @param categoryname the value for mallgoodskind.categoryName
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.logoUrl
     *
     * @return the value of mallgoodskind.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getLogourl() {
        return logourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.logoUrl
     *
     * @param logourl the value for mallgoodskind.logoUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setLogourl(String logourl) {
        this.logourl = logourl == null ? null : logourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.name
     *
     * @return the value of mallgoodskind.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.name
     *
     * @param name the value for mallgoodskind.name
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.standardPrice
     *
     * @return the value of mallgoodskind.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getStandardprice() {
        return standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.standardPrice
     *
     * @param standardprice the value for mallgoodskind.standardPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStandardprice(Integer standardprice) {
        this.standardprice = standardprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.salePrice
     *
     * @return the value of mallgoodskind.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.salePrice
     *
     * @param saleprice the value for mallgoodskind.salePrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSaleprice(Integer saleprice) {
        this.saleprice = saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.costPrice
     *
     * @return the value of mallgoodskind.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.costPrice
     *
     * @param costprice the value for mallgoodskind.costPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCostprice(Integer costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.barCode
     *
     * @return the value of mallgoodskind.barCode
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.barCode
     *
     * @param barcode the value for mallgoodskind.barCode
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.trafficPrice
     *
     * @return the value of mallgoodskind.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTrafficprice() {
        return trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.trafficPrice
     *
     * @param trafficprice the value for mallgoodskind.trafficPrice
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTrafficprice(Integer trafficprice) {
        this.trafficprice = trafficprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.trafficType
     *
     * @return the value of mallgoodskind.trafficType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTraffictype() {
        return traffictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.trafficType
     *
     * @param traffictype the value for mallgoodskind.trafficType
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTraffictype(Integer traffictype) {
        this.traffictype = traffictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.stock
     *
     * @return the value of mallgoodskind.stock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.stock
     *
     * @param stock the value for mallgoodskind.stock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.version
     *
     * @return the value of mallgoodskind.version
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.version
     *
     * @param version the value for mallgoodskind.version
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.tempStock
     *
     * @return the value of mallgoodskind.tempStock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTempstock() {
        return tempstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.tempStock
     *
     * @param tempstock the value for mallgoodskind.tempStock
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTempstock(Integer tempstock) {
        this.tempstock = tempstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.flowStatus
     *
     * @return the value of mallgoodskind.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getFlowstatus() {
        return flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.flowStatus
     *
     * @param flowstatus the value for mallgoodskind.flowStatus
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setFlowstatus(Integer flowstatus) {
        this.flowstatus = flowstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.state
     *
     * @return the value of mallgoodskind.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.state
     *
     * @param state the value for mallgoodskind.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.tempVersion
     *
     * @return the value of mallgoodskind.tempVersion
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getTempversion() {
        return tempversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.tempVersion
     *
     * @param tempversion the value for mallgoodskind.tempVersion
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setTempversion(Integer tempversion) {
        this.tempversion = tempversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.createTime
     *
     * @return the value of mallgoodskind.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.createTime
     *
     * @param createtime the value for mallgoodskind.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodskind.updateTime
     *
     * @return the value of mallgoodskind.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodskind.updateTime
     *
     * @param updatetime the value for mallgoodskind.updateTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}