package com.microshop.servicedao.dbmodel;

import java.util.Date;

public class Mallgoodspicture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private String pictureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mallgoodspicture.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.id
     *
     * @return the value of mallgoodspicture.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.id
     *
     * @param id the value for mallgoodspicture.id
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.goodsId
     *
     * @return the value of mallgoodspicture.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.goodsId
     *
     * @param goodsid the value for mallgoodspicture.goodsId
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid == null ? null : goodsid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.pictureUrl
     *
     * @return the value of mallgoodspicture.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public String getPictureurl() {
        return pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.pictureUrl
     *
     * @param pictureurl the value for mallgoodspicture.pictureUrl
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl == null ? null : pictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.sort
     *
     * @return the value of mallgoodspicture.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.sort
     *
     * @param sort the value for mallgoodspicture.sort
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.state
     *
     * @return the value of mallgoodspicture.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.state
     *
     * @param state the value for mallgoodspicture.state
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mallgoodspicture.createTime
     *
     * @return the value of mallgoodspicture.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mallgoodspicture.createTime
     *
     * @param createtime the value for mallgoodspicture.createTime
     *
     * @mbg.generated Tue Dec 26 19:10:23 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}